services:

  practice-app:
    image: bondar-academy/practice-app
    container_name: practice-app
    ports:
      - "4200:4200"

  playwright-runner:
    build: .
    container_name: playwright-runner
    depends_on:
      - practice-app
    environment:
      - BASE_URL=http://practice-app:4200

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""