services:
  bondar-practice-app:
    build:
      context: .
      dockerfile: Dockerfile.app # We will create this below
    ports:
      - "4201:80"

  playwright-runner:
    build: .
    environment:
      - BASE_URL=http://bondar-practice-app:80
    depends_on:
      - bondar-practice-app