version: '3.8'

services:
  bondar-practice-app:
    image: bondar-practice-app-practice-app:latest
    ports:
      - "4201:4200"

  playwright-runner:
    build: .
    environment:
      - BASE_URL=http://bondar-practice-app:4200
    depends_on:
      - bondar-practice-app