pipeline {
    agent any

    environment {
        // Ensure we use the correct Docker Compose path
        DOCKER_COMPOSE = '/usr/local/bin/docker compose'
    }

    stages {
        stage('Cleanup Environment') {
            script {
                echo "Cleaning up any old containers or hung ports..."
                // This ensures port 4201 is free before we start
                sh "${DOCKER_COMPOSE} down --remove-orphans || true"
            }
        }

        stage('Checkout SCM') {
            steps {
                // Jenkins automatically handles the main checkout
                echo "Checking out Playwright tests..."
            }
        }

        stage('Run Playwright Tests') {
            script {
                echo "Starting the Angular App..."
                // 1. Start the app in the background
                sh "${DOCKER_COMPOSE} up -d bondar-practice-app"

                // 2. Wait for Angular to 'Generate browser application bundles'
                // Based on Build 127, your app needs at least 2 minutes.
                echo "Waiting 150 seconds for Angular to compile..."
                sh "sleep 150"

                // 3. Run the Playwright container
                // --abort-on-container-exit ensures the whole stack stops when tests finish
                sh "${DOCKER_COMPOSE} up --build --abort-on-container-exit --exit-code-from playwright-runner"
            }
        }
    }

    post {
        always {
            script {
                echo "Extracting Test Report..."
                // We use the container name generated by Docker Compose
                sh "docker cp bondar-playwright-tests-playwright-runner-1:/app/playwright-report ./ || true"
                
                archiveArtifacts artifacts: 'playwright-report/**', allowEmptyArchive: true
                
                echo "Cleaning up..."
                sh "${DOCKER_COMPOSE} down"
            }
        }
    }
}